// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9lunQ6zZqBljm_ZNc-pwq9tnvp6v0PZ8',
    appId: '1:12610088768:web:0581de8c3be8ae0b3294a5',
    messagingSenderId: '12610088768',
    projectId: 'vehiculos-274be',
    authDomain: 'vehiculos-274be.firebaseapp.com',
    storageBucket: 'vehiculos-274be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfFtZPFfKvuXP1eIlL8m2Wk2is_NkfS20',
    appId: '1:12610088768:android:0dd876865ae214523294a5',
    messagingSenderId: '12610088768',
    projectId: 'vehiculos-274be',
    storageBucket: 'vehiculos-274be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsyvIZLB83vmq7OSdvh1ifugp7DGlISg8',
    appId: '1:12610088768:ios:3e3ed688ec495c9f3294a5',
    messagingSenderId: '12610088768',
    projectId: 'vehiculos-274be',
    storageBucket: 'vehiculos-274be.appspot.com',
    iosClientId: '12610088768-7n3grbsm1rp3adtnv16jti5hnqos81pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto118401136',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsyvIZLB83vmq7OSdvh1ifugp7DGlISg8',
    appId: '1:12610088768:ios:3e3ed688ec495c9f3294a5',
    messagingSenderId: '12610088768',
    projectId: 'vehiculos-274be',
    storageBucket: 'vehiculos-274be.appspot.com',
    iosClientId: '12610088768-7n3grbsm1rp3adtnv16jti5hnqos81pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto118401136',
  );
}
